drop database ASSM_JAVA4
create database ASSM_JAVA4
use ASSM_JAVA4

create table movie
(
	Id nvarchar(10),
	Genre nvarchar(50),
	MovieName nvarchar(100),
	MovieYear nvarchar(20),
	Note nvarchar(max),
	Background nvarchar(100),
	Photo nvarchar(100),
	primary key(Id)
)

drop table users
create table users
(
	UserId nvarchar(10),
	UserName nvarchar(50),
	Password nvarchar(100),
	Email nvarchar(100),
	Avatar nvarchar(max),
	Role bit,
	primary key(UserId)
)

Create table Favorite(
	idfv bigint identity(1,1) primary key,
	Id  nvarchar(10),
	UserId nvarchar(10),
	likedate date,
	foreign key (Id) references movie (Id),
	foreign key (UserId) references users (UserId)
);

select * from Favorite
SET IDENTITY_INSERT dbo.favorite On;
insert into Favorite values
('phim01','Hung123','02/24/2022')



delete users where UserId like 'Hung'
select * from users
insert into users values
('Hung123', N'Nguyễn Huỳnh Khuyết Hùng', '123', 'phiphung123bt@gmail.com', 'avatar_01.jpg', 1),
('Phuong123', N'Nguyễn Văn Phương', '123', 'phuong123@gmail.com', 'avatar_02.jpg', 0)


delete phim
select * from movie
insert into movie values
('phim01', 'UpcomingMovies', 'Doctor strange 2', '2022',N'Trong Doctor Strange của Marvel Studios trong Đa vũ trụ điên cuồng , MCU mở khóa Đa vũ trụ và đẩy ranh giới của nó ra xa hơn bao giờ hết. Hành trình vào thế giới vô danh với Doctor Strange , người, với sự giúp đỡ của các đồng minh thần bí cả cũ và mới, vượt qua những thực tại thay thế nguy hiểm và đáng sợ của Đa vũ trụ để đối đầu với một kẻ thù mới bí ẩn.', 'Doctorstrange.jpg', 'Doctorstrange.jpg'),
('phim02', 'UpcomingMovies', 'Spider-man: No way home', '2021',N'Lần đầu tiên trong lịch sử điện ảnh về Người Nhện , danh tính của người anh hùng trong khu dân cư thân thiện của chúng ta được tiết lộ, đưa trách nhiệm Siêu anh hùng của anh ta vào xung đột với cuộc sống bình thường của anh ta và khiến những người anh ta quan tâm nhất gặp rủi ro. Khi anh ta nhờ đến sự giúp đỡ của Doctor Strange để khôi phục lại bí mật của mình, câu thần chú đã xé toạc một lỗ hổng trong thế giới của họ, giải phóng những kẻ phản diện mạnh nhất từng chiến đấu với Người Nhện trong bất kỳ vũ trụ nào. Bây giờ, Peter sẽ phải vượt qua thử thách lớn nhất của mình, điều này sẽ không chỉ thay đổi vĩnh viễn tương lai của chính anh ấy mà còn là tương lai của Đa vũ trụ . ', 'Spider-mannowayhome.jpg','Spider-mannowayhome.jpg'),
('phim03', 'UpcomingMovies', 'Eternals', '2021',N'Eternals là một chủng tộc của những sinh vật tổng hợp gần như bất tử được tạo ra bởi Celestials . Họ được gửi đến nhiều hành tinh để bảo vệ và giúp phát triển các dạng sống có tri giác để cung cấp năng lượng cho một hạt giống Thiên thể bên trong hành tinh, hạt giống này sẽ hấp thụ năng lượng được tạo ra từ các dạng sống có tri giác. Mười trong số những Eternals này đã đến Trái đất trong thời kỳ đồ đá để bảo vệ nhân loại khỏi các Deviant .','Eternals.jpg','Eternals.jpg'),
('phim04', 'UpcomingMovies', 'Shang-Chi and The Legend of The Ten Rings', '2021',N'Shang-Chi phải đối mặt với quá khứ mà anh nghĩ rằng anh đã bỏ lại khi bị lôi kéo vào trang web của tổ chức Mười chiếc nhẫn bí ẩn .','Shangchi.jpg' ,'Shangchi.jpg'),
('phim05', 'UpcomingMovies', 'Black Widow', '2021',N'Trong bộ phim kinh dị hành động về điệp viên Black Widow của Marvel Studios , Natasha Romanoff, hay còn gọi là Góa phụ đen , đối mặt với những phần đen tối hơn trong cuốn sổ cái của cô khi một âm mưu nguy hiểm liên quan đến quá khứ của cô nảy sinh. Bị truy đuổi bởi một thế lực không thể nào hạ gục được cô, Natasha phải đối mặt với lịch sử làm điệp viên và những mối quan hệ tan vỡ đã để lại cho cô từ lâu trước khi cô trở thành một Avenger .', 'Blackwidow.jpg','Blackwidow.jpg'),
('phim06', 'UpcomingMovies', 'Spider-man: Far from home', '2021',N'Peter Parker trở lại trong Spider-Man: Far From Home , chương tiếp theo của loạt phim Spider-Man: Homecoming ! Khu phố thân thiện Super Hero của chúng ta quyết định cùng những người bạn thân nhất của mình Ned , MJ và những người còn lại trong băng nhóm đi nghỉ ở Châu Âu . Tuy nhiên, kế hoạch của Peter để lại những siêu anh hùng trong vài tuần nhanh chóng bị hủy bỏ khi anh ta miễn cưỡng đồng ý giúp Nick Fury khám phá bí ẩn về một số cuộc tấn công của sinh vật nguyên tố , tạo ra sự tàn phá trên khắp lục địa!','Spider-manfarfromhome.jpg', 'Spider-manfarfromhome.jpg'),
('phim07', 'TopRatedMovies', 'Avengers: Age Of Ultron', '2015',N'Marvel Studios giới thiệu Avengers: Age of Ultron , phần tiếp theo sử thi của bộ phim Siêu anh hùng lớn nhất mọi thời đại . Khi Tony Stark cố gắng bắt đầu một chương trình gìn giữ hòa bình không hoạt động, mọi thứ trở nên tồi tệ và những Anh hùng mạnh nhất của Trái đất, bao gồm Iron Man , Captain America , Thor , Hulk , Black Widow và Hawkeye , cùng với sự hỗ trợ từ Nick Fury và Maria Hill được đưa lên đỉnh điểm kiểm tra như số phận của hành tinh bị treo trong sự cân bằng. Khi Ultron phản diện xuất hiện, đó là tùy thuộc vào Avengersđể ngăn anh ta thực hiện những kế hoạch khủng khiếp của mình , và sớm liên minh không dễ dàng và hành động bất ngờ mở đường cho một cuộc phiêu lưu toàn cầu hoành tráng và độc đáo.','AvengersAgeOfUltron.jpg' ,'AvengersAgeOfUltron.jpg'),
('phim08', 'TopRatedMovies', 'Avengers: Infinity War', '2018',N'Một hành trình điện ảnh chưa từng có trong mười năm hình thành và kéo dài toàn bộ Vũ trụ Điện ảnh Marvel , " Avengers: Infinity War " của Marvel Studios mang đến cho màn ảnh trận đấu cuối cùng, chết chóc nhất mọi thời đại. Khi Avengers và các đồng minh của họ tiếp tục bảo vệ thế giới khỏi những mối đe dọa quá lớn mà bất kỳ anh hùng nào có thể xử lý, một mối nguy hiểm mới đã xuất hiện từ bóng tối vũ trụ: Thanos . Là một kẻ khét tiếng giữa các thiên hà, mục tiêu của anh ta là thu thập tất cả sáu Viên đá Vô cực , những đồ tạo tác của sức mạnh không thể tưởng tượng được, và sử dụng chúng để gây ra ý chí vặn vẹo của anh ta trên tất cả thực tế. Tất cả mọi thứ mà các Avengers đã chiến đấu cho đến thời điểm này - số phận củaTrái đất và bản thân sự tồn tại chưa bao giờ chắc chắn hơn thế.','AvengersInfinityWar.jpg', 'AvengersInfinityWar.jpg'),
('phim09', 'TopRatedMovies', 'Avengers: End Game', '2019',N'Quá trình nghiêm trọng của các sự kiện được thực hiện bởi Thanos đã xóa sổ một nửa vũ trụ và phá vỡ hàng ngũ Avengers , buộc các Avengers còn lại phải đứng cuối cùng trong kết thúc lớn của Marvel Studios cho 22 bộ phim, Avengers: Endgame .', 'AvengersEndGame.jpg', 'AvengersEndGame.jpg'),
('phim10', 'TopRatedMovies', 'Captain America: Civil War', '2016',N'Captain America: Civil War của Marvel phát hiện Steve Rogers dẫn đầu đội Avengers mới thành lập trong nỗ lực không ngừng để bảo vệ nhân loại. Nhưng sau một sự cố khác liên quan đến Avengers dẫn đến thiệt hại tài sản thế chấp, áp lực chính trị gia tăng để cài đặt một hệ thống trách nhiệm giải trình , do một cơ quan quản lý đứng đầu để giám sát và chỉ đạo đội. Hiện trạng mới phá vỡ các Avengers, dẫn đến hai phe - một do Steve Rogers lãnh đạo và mong muốn của anh ta để Avengers vẫn tự do bảo vệ nhân loại mà không có sự can thiệp của chính phủ, và phe kia theo quyết định đáng ngạc nhiên của Tony Stark để hỗ trợ sự giám sát của chính phủ và trách nhiệm giải trình','captainamericacivilwar.jpg', 'captainamericacivilwar.jpg'),
('phim11', 'TopRatedMovies', 'Doctor Strange', '2016',N'Từ Marvel Studios là Doctor Strange , câu chuyện về bác sĩ phẫu thuật thần kinh nổi tiếng thế giới, Tiến sĩ Stephen Strange , người có cuộc đời thay đổi mãi mãi sau một tai nạn xe hơi kinh hoàng cướp đi quyền sử dụng đôi tay của anh. Khi y học cổ truyền không thành công với anh ta, anh ta buộc phải tìm cách chữa trị và hy vọng, ở một nơi không thể - một vùng đất bí ẩn được gọi là Kamar-Taj . Anh nhanh chóng biết rằng đây không chỉ là một trung tâm chữa bệnh mà còn là tiền tuyến của cuộc chiến chống lại những thế lực đen tối vô hình đang muốn phá hủy thực tại của chúng ta. Không lâu sau, Strange - được trang bị sức mạnh phép thuật mới có được - buộc phải lựa chọn quay trở lại cuộc sống giàu có và địa vị của mình hay bỏ lại tất cả để bảo vệ thế giới với tư cách là phù thủy quyền năng nhất tồn tại.' ,'Doctorstrange.jpg','Doctorstrange.jpg'),
('phim12', 'TopRatedMovies', 'Guardians Of The Galaxy', '2014',N'Một cuộc phiêu lưu không gian hoành tráng, đầy hành động, "Guardians of the Galaxy" của Marvel, mở rộng Vũ trụ Điện ảnh Marvel sang vũ trụ, nơi nhà thám hiểm dũng cảm Peter Quill nhận thấy mình là đối tượng của một cuộc săn tiền thưởng không ngừng sau khi đánh cắp một quả cầu bí ẩn mà Ronan thèm muốn , nhân vật phản diện mạnh mẽ với tham vọng đe dọa toàn bộ vũ trụ. Để trốn tránh Ronan luôn dai dẳng, Quill buộc phải ký một thỏa thuận đình chiến không dễ dàng với một bộ tứ những kẻ bất lợi khác nhau - Rocket , một con gấu trúc có súng; Groot , một hình người giống cây; Gamora chết chóc và bí ẩn ; và Drax the Destroyer được điều khiển bởi sự trả thù. Nhưng khi Quill phát hiện ra sức mạnh thực sự của quả cầu và mối đe dọa mà nó gây ra cho vũ trụ, anh ta phải cố gắng hết sức để tập hợp các đối thủ ragtag của mình cho một vị trí cuối cùng, tuyệt vọng - với số phận của thiên hà trong sự cân bằng.','GuardiansoftheGalaxy.jpg', 'GuardiansoftheGalaxy.jpg'),
('phim13', 'TopRatedMovies', 'Spider-man: Home Coming', '2017', N'Một Peter Parker / Người Nhện trẻ tuổi , người đã xuất hiện lần đầu tiên gây xúc động trong Captain America: Civil War , bắt đầu tìm ra danh tính mới của mình là siêu anh hùng lướt web trong Spider-Man: Homecoming . Xúc động với trải nghiệm của mình với Avengers , Peter trở về nhà, nơi anh sống với dì May của mình , dưới sự giám sát của người cố vấn mới Tony Stark . Peter cố gắng trở lại với thói quen hàng ngày bình thường của mình - bị phân tâm bởi những suy nghĩ về việc chứng tỏ bản thân không chỉ là Người Nhện hàng xóm thân thiện của bạn - nhưng khi Vulture nổi lên như một nhân vật phản diện mới, mọi thứ mà Peter nắm giữ quan trọng nhất sẽ bị đe dọa','Spider-manHomeComing.jpg','Spider-manHomeComing.jpg'),
('phim14', 'TopRatedMovies', 'Thor: Ragnarok', '2017',N'Thế giới của Thor sắp bùng nổ trong Marvels Thor: Ragnarok . Người anh trai quỷ quyệt của anh, Loki , đã chiếm lấy Asgard , Hela mạnh mẽ nổi lên để cướp ngai vàng cho chính mình và Thor bị giam cầm ở phía bên kia của vũ trụ . Để thoát khỏi sự giam cầm và cứu ngôi nhà của mình khỏi sự hủy diệt sắp xảy ra, Thor trước tiên phải giành chiến thắng trong một cuộc thi chết người ngoài hành tinh bằng cách đánh bại đồng minh cũ và đồng đội Avenger ... The Incredible Hulk !', 'ThorRagnarok.jpg','ThorRagnarok.jpg'),
('phim15', 'LatesMovies', 'Ant-man', '2015',N'Sự phát triển tiếp theo của Vũ trụ Điện ảnh Marvel lần đầu tiên đưa một thành viên sáng lập của The Avengers lên màn ảnh rộng với bộ phim " Ant-Man " của Marvel Studios . Được trang bị khả năng đáng kinh ngạc khi thu nhỏ quy mô nhưng tăng sức mạnh, tên trộm bậc thầy Scott Lang phải nắm lấy người anh hùng bên trong của mình và giúp người cố vấn của anh ta, Bác sĩ Hank Pym , bảo vệ bí mật đằng sau bộ đồ Ant-Man ngoạn mục của anh ta khỏi một thế hệ mối đe dọa cao ngất ngưởng mới . Chống lại những trở ngại dường như không thể vượt qua, Pym và Lang phải lập kế hoạch và thực hiện một vụ trộm sẽ giải cứu thế giới.','Ant-man.jpg', 'Ant-man.jpg'),
('phim16', 'LatesMovies', 'Ant-man 2', '2018',N'Từ Vũ trụ Điện ảnh Marvel , một chương mới có các anh hùng có khả năng thu nhỏ đáng kinh ngạc: Ant-Man and the Wasp . Trong hậu quả của Captain America: Civil War , Scott Lang phải vật lộn với hậu quả của những lựa chọn vừa là siêu anh hùng vừa là một người cha. Khi anh ấy đấu tranh để cân bằng lại cuộc sống gia đình của mình với trách nhiệm của mình với tư cách là Người Kiến, anh ấy phải đối mặt với Hope van Dyne và Tiến sĩ Hank Pym với một nhiệm vụ mới khẩn cấp. Scott một lần nữa phải mặc lại bộ đồ và học cách chiến đấu bên cạnh The Wasp khi cả nhóm làm việc cùng nhau để khám phá những bí mật từ quá khứ của họ.', 'AntMan2.jpg','AntMan2.jpg'),
('phim17', 'LatesMovies', 'Black Panther', '2018',N'Black Panther của Marvel Studios theo chân TChalla , người, sau các sự kiện của Captain America: Civil War , trở về quê hương của quốc gia châu Phi bị cô lập, có công nghệ tiên tiến Wakanda để thay thế vị trí Vua của mình. Tuy nhiên, khi kẻ thù cũ xuất hiện trở lại trên radar, dũng khí của TChalla với tư cách là Vua và Báo đen được thử thách khi anh bị lôi kéo vào một cuộc xung đột khiến toàn bộ số phận của Wakanda và thế giới gặp rủi ro.','BlackPanther.jpg', 'BlackPanther.jpg'),
('phim18', 'LatesMovies', 'Captain America: The first Avengers', '2011',N'Marvels Captain America: The First Avenger tập trung vào những ngày đầu của Vũ trụ Marvel khi Steve Rogers tình nguyện tham gia vào một chương trình thử nghiệm biến anh ta thành Siêu chiến binh được gọi là Captain America.','Captainamerica.jpg', 'Captainamerica.jpg'),
('phim19', 'LatesMovies', 'Captain America: The Winter Soldier', '2014',N'Sau trận đại hồng thủy ở New York với The Avengers , Captain America: The Winter Soldier của Marvel , tìm thấy Steve Rogers , hay còn gọi là Captain America, đang sống lặng lẽ ở Washington, DC và cố gắng thích nghi với thế giới hiện đại. Nhưng khi một đồng nghiệp của SHIELD bị tấn công, Steve bị cuốn vào một mạng lưới âm mưu có nguy cơ khiến thế giới gặp nguy hiểm. Tham gia lực lượng với Góa phụ đen , Captain America đấu tranh để vạch trần âm mưu ngày càng mở rộng trong khi chiến đấu chống lại những sát thủ chuyên nghiệp được cử đến để bịt miệng anh ta mọi lúc mọi nơi. Khi phạm vi đầy đủ của âm mưu phản diệnđược tiết lộ, Captain America và Black Widow tranh thủ sự giúp đỡ của một đồng minh mới, Falcon . Tuy nhiên, họ sớm phải đối mặt với một kẻ thù bất ngờ và đáng gờm - Winter Soldier .','Captainamericathewintersoldier.jpg', 'Captainamericathewintersoldier.jpg'),
('phim20', 'LatesMovies', 'Iron Man', '2008',N'Người Sắt năm 2008 kể câu chuyện về Tony Stark , một tỷ phú công nghiệp và nhà phát minh thiên tài, người bị bắt cóc và buộc phải chế tạo một loại vũ khí tàn khốc. Thay vào đó, sử dụng trí thông minh và sự khéo léo của mình, Tony chế tạo một bộ áo giáp công nghệ cao và thoát khỏi nơi giam cầm. Khi phát hiện ra một âm mưu bất chính với những tác động toàn cầu, anh ta mặc bộ áo giáp mạnh mẽ của mình và thề sẽ bảo vệ thế giới với tư cách là Người Sắt.','Ironman.jpg', 'Ironman.jpg'),
('phim21', 'LatesMovies', 'Iron Man 2', '2010',N'Với việc cả thế giới giờ đây đã biết rằng anh ta là Người Sắt, nhà phát minh tỷ phú Tony Stark phải đối mặt với áp lực từ mọi phía để chia sẻ công nghệ của mình với quân đội . Anh không muốn tiết lộ bí mật về bộ giáp của mình , vì sợ thông tin sẽ rơi vào tay kẻ xấu. Với Pepper Potts và "Rhodey" Rhodes bên cạnh, Tony phải hình thành các liên minh mới và đối đầu với một kẻ thù mới mạnh mẽ .' ,'Ironman2.jpg','Ironman2.jpg'),
('phim22', 'LatesMovies', 'Thor', '2011',N'Là con trai của Odin , vua của các vị thần Bắc Âu, Thor sẽ sớm thừa kế ngai vàng Asgard từ người cha già của mình. Tuy nhiên, vào ngày mà anh ấy sẽ được đăng quang, Thor phản ứng tàn bạo khi kẻ thù của các vị thần, Frost Giants , vào cung điện vi phạm hiệp ước của họ. Để trừng phạt, Odin trục xuất Thor xuống Trái đất . Trong khi Loki , anh trai của Thor, âm mưu nghịch ngợm ở Asgard, Thor, giờ đã bị tước bỏ sức mạnh, phải đối mặt với mối đe dọa lớn nhất của mình .','thor.jpg', 'thor.jpg'),
('phim23', 'EnglishMovies', 'X-Men: Dark Phoenix', '2019',N'Jean Grey gần như bị giết trong một nhiệm vụ giải cứu ngoài không gian khi cô bị tấn công bởi một lực lượng vũ trụ bí ẩn. Khi trở về nhà, lực lượng này khiến Jean trở nên mạnh mẽ hơn nhiều và bất ổn hơn rất nhiều. Jean, mất kiểm soát sức mạnh của chính mình, bắt đầu vén màn kết cấu giữ các X-Men lại với nhau. Với việc các X-Men tan rã, họ phải tìm cách đoàn kết để cứu linh hồn của Jean và hành tinh của chúng ta khỏi những kẻ ngoài hành tinh muốn sử dụng lực lượng này để thống trị thiên hà. ','darkphoenix.jpg', 'darkphoenix.jpg'),
('phim24', 'EnglishMovies', 'Deadpool', '2016',N'Deadpool xoay quanh anh chàng Wade Wilson, một người bị ung thư vô phương cứu chữa bị thí nghiệm trở thành dị nhân với khả năng phục hồi siêu tốc giống Wolverine nhưng ưu việt hơn, mặc dù để lại sẹo sau cuộc thí nghiệm khiến anh trở nên xấu xí. Mất đi vẻ ngoài, người yêu, hạnh phúc, điều đó khiến anh bằng mọi giá tìm ra kẻ đã phá hoại cuộc đời anh.','deadpool.jpg', 'deadpool.jpg'),
('phim25', 'EnglishMovies', 'Deadpool 2', '2018',N'Hai năm sau khi thành công với vai trò lính đánh thuê Deadpool, Wade Wilson bị một nhóm người xông vào nhà ngay trong đêm mà Wade và Vanessa có ý định cùng nhau lập gia đình. Wade đã dùng bộ dao bếp để tiêu diệt kẻ địch. Tuy nhiên khi đã sử dụng hết dao bếp, chỉ còn lại chiếc dao quệt kem thì bất ngờ một tên địch nữa xông vào bắn chết Vanessa. Wade giết hắn để trả thù, nhưng anh luôn tự trách mình vì cái chết của vợ chưa cưới. Những ngày tháng tiếp theo, Wade liên tục tìm cách tự tử, và cách cuối cùng anh làm là nằm lên thùng đựng xăng và châm lửa để được gặp lại Vanessa ở thế giới bên kia.','deadpool2.jpg', 'deadpool2.jpg'),
('phim26', 'EnglishMovies', 'Logan', '2017',N'Logan được tiếp cận bởi Gabriela, một y tá của Transigen, người yêu cầu anh hộ tống cô và một bé gái 11 tuổi, Laura, đến một nơi ở Bắc Dakota được gọi là "Eden". Sau khi miễn cưỡng chấp nhận công việc, Logan phát hiện ra rằng Gabriela đã bị sát hại. Anh, Xavier và Laura trong gang tấc thoát khỏi những kẻ giết cô - Donald Pierce và những người thực thi điều khiển học được tăng cường, Reavers - nhưng Caliban bị bắt và tra tấn để buộc anh phải sử dụng sức mạnh đột biến của mình để theo dõi chúng. Logan và Xavier biết được qua một đoạn video trên điện thoại của Gabriela rằng Transigen đang nhân giống những đứa trẻ đột biến với mẫu DNA của một số dị nhân, nhưng khi hoàn thành dự án "X-24", những đứa trẻ đó sẽ bị xử tử. Gabriela đã giúp một số trẻ em trốn thoát khỏi khu phức hợp Transigen trước khi đưa Laura qua biên giới.', 'logan.jpg','logan.jpg'),
('phim27', 'EnglishMovies', 'X-Men: Apocalypse', '2016',N'Ở Ba Lan, Erik đang ở cùng vợ và con gái Nina. Erik đã không may bộc lộ khả năng của mình để cứu một người công nhân. Những người làm việc ở đó đã báo sự việc này với cảnh sát và trong lúc đụng độ đó thì con gái và vợ của Erik vô tình bị bắn chết. Thương tiếc gia đình mình, Erik đã giết hết tất cả viên cảnh sát. En Sabah Nur tìm đến Erik và đưa anh đến trại tập trung Auschwits, nơi anh lần đầu tiên phát huy khả năng của mình. Erik phá hủy khu trại và gia nhập nhóm Tứ Kị Sĩ.', 'x-menapocalypse.jpg','x-menapocalypse.jpg'),
('phim28', 'EnglishMovies', 'X-Men: Days of Future Past', '2014', N'Ở Ba Lan, Erik đang ở cùng vợ và con gái Nina. Erik đã không may bộc lộ khả năng của mình để cứu một người công nhân. Những người làm việc ở đó đã báo sự việc này với cảnh sát và trong lúc đụng độ đó thì con gái và vợ của Erik vô tình bị bắn chết. Thương tiếc gia đình mình, Erik đã giết hết tất cả viên cảnh sát. En Sabah Nur tìm đến Erik và đưa anh đến trại tập trung Auschwits, nơi anh lần đầu tiên phát huy khả năng của mình. Erik phá hủy khu trại và gia nhập nhóm Tứ Kị Sĩ.','x-mendaysoffuturepast.jpg','x-mendaysoffuturepast.jpg')